UPDATE  CORE_ITEM SET LAST_UPDATED=now() ;
CREATE UNIQUE INDEX IF NOT EXISTS uk_sale_customer_tin ON SALE_CUSTOMER (CUSTOMER_TIN);
UPDATE CORE_ITEM SET UNIT_COST = 0 WHERE UNIT_COST IS NULL;
UPDATE CORE_ITEM SET UNIT_PRICE = 0 WHERE UNIT_PRICE IS NULL;
ALTER TABLE CORE_ITEM ALTER COLUMN UNIT_PRICE SET DEFAULT 0,ALTER COLUMN UNIT_PRICE SET NOT NULL;
ALTER TABLE CORE_ITEM ALTER COLUMN UNIT_COST SET DEFAULT 0,ALTER COLUMN UNIT_COST SET NOT NULL;