---Category & Brand Distribution (Pie Charts)
SELECT c.CATEGORY_NAME, SUM(s.QUANTITY)FROM INVENTORY_WAREHOUSE_STOCK s JOIN CORE_ITEM p ON s.ITEM_ID = p.id JOIN CORE_ITEM_CATEGORY c ON p.CATEGORY_ID = c.id GROUP BY c.CATEGORY_NAME;
----Brand
SELECT c.BRAND_NAME, SUM(s.QUANTITY)FROM INVENTORY_WAREHOUSE_STOCK s JOIN CORE_ITEM p ON s.ITEM_ID = p.id JOIN CORE_ITEM_BRAND c ON p.BRAND_ID = c.id GROUP BY c.BRAND_NAME;
